### ISSUE TITLE
The release time of  code

### ISSUE THREAD

**Issue by Sugar55888** [wuminye/ImplicitGS#1]
Thank for your nice work! Is there any plan about the release time?

**Comment by wuminye** [comment]
Thank you for your interest in our work. The code is now available.

**Comment by Sugar55888** [comment]
@wuminye Hi, it seems that repository does not contain the train script as mentioned in readme.md. Could you provide them?

**Comment by wuminye** [comment]
Thank you for your reminder, the missing file has been uploaded.
